### ISSUE TITLE
Consider changing the pronoun? Thanks. 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/redux-forms-codealong#12]
All this code does is say that every time the user changes the input field (that is, whenever he --ADD She, or They, or something other than "he" alone. Thanks!! --types something in) we should call our handleChange() function (which we haven't written yet).

**Comment by maxwellbenton** [comment]
Hi @MiriamPeskowitz,

Thank you for spotting this and providing feedback. We've updated this lesson's Readme and removed pronouns entirely from this lesson.

Thank you for contributing to this lesson!
