### ISSUE TITLE
Example code produces a different result than noted

### ISSUE THREAD

**Issue by afteralec** [learn-co-curriculum/redux-forms-codealong#32]
Hi!

In a middle paragraph of this lab, the readme states that the `todos` array should look like:

`[{text: "walk dog"}, {text: "call mom"}]`

But then in the actual reducer, we do:

`return { todos: state.todos.concat(action.payload.text) };`

This will just keep adding *only* the *text* of each `todo` object onto the array, resulting in:

`["walk dog", "call mom"]`

I recommend removing the `payload` component of this lab's code altogether and editing the Readme or correcting the reducer so that it concats `action.payload` instead of `action.payload.text` to produce the result noted in the above paragraph

**Comment by ihollander** [comment]
Closed by https://github.com/learn-co-curriculum/redux-forms-codealong/commit/f1f38d52baade464f9d995ea08ee028e29e33aa7
