### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by efl7a** [learn-co-curriculum/redux-forms-codealong#5]
The typo below prevents the code from compiling.  It would be a big help though if you talked more about the react-redux components that you use in this lesson.  

export default connect(null, mapDispatchToProps)(connectCreateTodo);

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @efl7a.

We have updated the materials to fix the typo, added some additional discussion and examples of setting up `connect` and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
