### ISSUE TITLE
No logging in console at end of codealong

### ISSUE THREAD

**Issue by kostanzhoglo** [learn-co-curriculum/redux-forms-codealong#7]
Hello,

Just re-did this lab in v6, and at the end of the lab, it says we should see our actions and state being logged in the console.
But nothing is happening.

It's because the earlier code in createTodo.js has this code:
  **handleSubmit = event => {
    event.preventDefault()
    this.props.dispatch({ type: "EXAMPLE", payload: this.state })
  }**

**type: "EXAMPLE"** needs to be changed to...
**type: "ADD_TODO"**

please fix in the README.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @kostanzhoglo.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
