### ISSUE TITLE
code along mapDispatchToProps does not work

### ISSUE THREAD

**Issue by emikojima** [learn-co-curriculum/redux-forms-codealong#9]
This code provided in the code along does not work (error: 'mapDispatchToProps' is not defined):
mapDispatchToProps = dispatch => {
  return {
    addTodo: formData => dispatch({ type: 'ADD_TODO', payload: formData })
  }
}
This syntax works: 
const mapDispatchToProps = dispatch => ({
    addTodo: formData => dispatch({ type: 'ADD_TODO', payload: formData })
})

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @emikojima!

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
